//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoteEducationApplication.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RemoteEducationApplication.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ƎEducation.
        /// </summary>
        public static string ApplicationWindowTitle {
            get {
                return ResourceManager.GetString("ApplicationWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelAction {
            get {
                return ResourceManager.GetString("CancelAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string ClientControlScore {
            get {
                return ResourceManager.GetString("ClientControlScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client has disconnected....
        /// </summary>
        public static string ClientStatusDisconnected {
            get {
                return ResourceManager.GetString("ClientStatusDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for desktop image....
        /// </summary>
        public static string ClientStatusImageWait {
            get {
                return ResourceManager.GetString("ClientStatusImageWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string ClientWindowConnected {
            get {
                return ResourceManager.GetString("ClientWindowConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to connect....
        /// </summary>
        public static string ClientWindowConnectTry {
            get {
                return ResourceManager.GetString("ClientWindowConnectTry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting....
        /// </summary>
        public static string ClientWindowProcessWaiting {
            get {
                return ResourceManager.GetString("ClientWindowProcessWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string ClientWindowsDisconnected {
            get {
                return ResourceManager.GetString("ClientWindowsDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending Image....
        /// </summary>
        public static string ClientWindowSendingImage {
            get {
                return ResourceManager.GetString("ClientWindowSendingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected exception - {0}.
        /// </summary>
        public static string ExceptionMailSubject {
            get {
                return ResourceManager.GetString("ExceptionMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error has occured at {0:t}..
        /// </summary>
        public static string ExceptionWindowMessage {
            get {
                return ResourceManager.GetString("ExceptionWindowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send mail.
        /// </summary>
        public static string ExceptionWindowSendMail {
            get {
                return ResourceManager.GetString("ExceptionWindowSendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send an email with detailed description how this error has occured..
        /// </summary>
        public static string ExceptionWindowSendMailTooltip {
            get {
                return ResourceManager.GetString("ExceptionWindowSendMailTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short description:.
        /// </summary>
        public static string ExceptionWindowShortDescription {
            get {
                return ResourceManager.GetString("ExceptionWindowShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ExceptionWindowTitle {
            get {
                return ResourceManager.GetString("ExceptionWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        public static string FileSubMenuItemExit {
            get {
                return ResourceManager.GetString("FileSubMenuItemExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string LoginPageClear {
            get {
                return ResourceManager.GetString("LoginPageClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name:.
        /// </summary>
        public static string LoginPageFullName {
            get {
                return ResourceManager.GetString("LoginPageFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginPageLogin {
            get {
                return ResourceManager.GetString("LoginPageLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking identity.
        /// </summary>
        public static string LoginPageLoginLoadingText {
            get {
                return ResourceManager.GetString("LoginPageLoginLoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        public static string LoginPageLoginTitle {
            get {
                return ResourceManager.GetString("LoginPageLoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string LoginPagePassword {
            get {
                return ResourceManager.GetString("LoginPagePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string LoginPageRecovery {
            get {
                return ResourceManager.GetString("LoginPageRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating new password.
        /// </summary>
        public static string LoginPageRecoveryLoadingText {
            get {
                return ResourceManager.GetString("LoginPageRecoveryLoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECOVERY.
        /// </summary>
        public static string LoginPageRecoveryTitle {
            get {
                return ResourceManager.GetString("LoginPageRecoveryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string LoginPageUserName {
            get {
                return ResourceManager.GetString("LoginPageUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        public static string MenuFileLogoff {
            get {
                return ResourceManager.GetString("MenuFileLogoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MenuHelpAbout {
            get {
                return ResourceManager.GetString("MenuHelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Help.
        /// </summary>
        public static string MenuHelpViewHelp {
            get {
                return ResourceManager.GetString("MenuHelpViewHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Options.
        /// </summary>
        public static string MenuOptions {
            get {
                return ResourceManager.GetString("MenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic.
        /// </summary>
        public static string MenuThemeClassic {
            get {
                return ResourceManager.GetString("MenuThemeClassic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string MenuThemeDark {
            get {
                return ResourceManager.GetString("MenuThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        public static string MenuThemeOrange {
            get {
                return ResourceManager.GetString("MenuThemeOrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        public static string MenuView {
            get {
                return ResourceManager.GetString("MenuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scores.
        /// </summary>
        public static string MenuWindowScoreListTitle {
            get {
                return ResourceManager.GetString("MenuWindowScoreListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Scores.
        /// </summary>
        public static string OptionsSubMenuScoreList {
            get {
                return ResourceManager.GetString("OptionsSubMenuScoreList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answers:.
        /// </summary>
        public static string QuestionDetailsAnswers {
            get {
                return ResourceManager.GetString("QuestionDetailsAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty:.
        /// </summary>
        public static string QuestionDetailsDifficulty {
            get {
                return ResourceManager.GetString("QuestionDetailsDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject:.
        /// </summary>
        public static string QuestionDetailsSubject {
            get {
                return ResourceManager.GetString("QuestionDetailsSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        public static string QuestionDetailsTitle {
            get {
                return ResourceManager.GetString("QuestionDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded by:.
        /// </summary>
        public static string QuestionDetailsUploadedBy {
            get {
                return ResourceManager.GetString("QuestionDetailsUploadedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question details.
        /// </summary>
        public static string QuestionDetailsWindowTitle {
            get {
                return ResourceManager.GetString("QuestionDetailsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string QuestionSelectDetails {
            get {
                return ResourceManager.GetString("QuestionSelectDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty:.
        /// </summary>
        public static string QuestionSelectDifficulty {
            get {
                return ResourceManager.GetString("QuestionSelectDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string QuestionSelectDifficultyDefault {
            get {
                return ResourceManager.GetString("QuestionSelectDifficultyDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string QuestionSelectEdit {
            get {
                return ResourceManager.GetString("QuestionSelectEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string QuestionSelectFilter {
            get {
                return ResourceManager.GetString("QuestionSelectFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string QuestionSelectSend {
            get {
                return ResourceManager.GetString("QuestionSelectSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        public static string QuestionSelectSort {
            get {
                return ResourceManager.GetString("QuestionSelectSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date created:.
        /// </summary>
        public static string QuestionSelectSortDateCreated {
            get {
                return ResourceManager.GetString("QuestionSelectSortDateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded by:.
        /// </summary>
        public static string QuestionSelectSortName {
            get {
                return ResourceManager.GetString("QuestionSelectSortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        public static string QuestionSelectSortTitle {
            get {
                return ResourceManager.GetString("QuestionSelectSortTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject:.
        /// </summary>
        public static string QuestionSelectSubjectText {
            get {
                return ResourceManager.GetString("QuestionSelectSubjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded by:.
        /// </summary>
        public static string QuestionSelectUploadedBy {
            get {
                return ResourceManager.GetString("QuestionSelectUploadedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select question.
        /// </summary>
        public static string QuestionSelectWindowTitle {
            get {
                return ResourceManager.GetString("QuestionSelectWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover.
        /// </summary>
        public static string RecoveryAction {
            get {
                return ResourceManager.GetString("RecoveryAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other connected clients.
        /// </summary>
        public static string SideClientBarHeader {
            get {
                return ResourceManager.GetString("SideClientBarHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections.
        /// </summary>
        public static string StatusBarConnections {
            get {
                return ResourceManager.GetString("StatusBarConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections updated.
        /// </summary>
        public static string StatusBarLastConnectionRefresh {
            get {
                return ResourceManager.GetString("StatusBarLastConnectionRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image updated.
        /// </summary>
        public static string StatusBarLastImageRefresh {
            get {
                return ResourceManager.GetString("StatusBarLastImageRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Questions.
        /// </summary>
        public static string SubMenuQuestions {
            get {
                return ResourceManager.GetString("SubMenuQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Select.
        /// </summary>
        public static string SubMenuQuestionSelect {
            get {
                return ResourceManager.GetString("SubMenuQuestionSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Upload.
        /// </summary>
        public static string SubMenuQuestionUpload {
            get {
                return ResourceManager.GetString("SubMenuQuestionUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full screen.
        /// </summary>
        public static string SubMenuViewFullScreen {
            get {
                return ResourceManager.GetString("SubMenuViewFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string SubMenuViewTheme {
            get {
                return ResourceManager.GetString("SubMenuViewTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string UserDataEmail {
            get {
                return ResourceManager.GetString("UserDataEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string WindowBarClose {
            get {
                return ResourceManager.GetString("WindowBarClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string WindowBarConnect {
            get {
                return ResourceManager.GetString("WindowBarConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand.
        /// </summary>
        public static string WindowBarExpand {
            get {
                return ResourceManager.GetString("WindowBarExpand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string WindowBarMinimize {
            get {
                return ResourceManager.GetString("WindowBarMinimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shrink.
        /// </summary>
        public static string WindowBarShrink {
            get {
                return ResourceManager.GetString("WindowBarShrink", resourceCulture);
            }
        }
    }
}
